import { invoke, projectHomepage, toast } from "../../shared/tauri.js";

const icons = { projects: "▣", image: "◎", chat: "□", canvas: "▦", assets: "▤", api: "⌘", settings: "⚙", announcements: "●", homepage: "◉" };
const routeLabels = { projects: "项目管理", image: "在线生图", chat: "GPT 对话", canvas: "无限画布", assets: "素材库", api: "API 设置", settings: "更多设置" };
const state = { route: "projects", projects: [], currentProject: null, sessions: [], session: null, assets: [], generated: null, selection: new Set(), view: { x: 0, y: 0, scale: 1 } };
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]);
const formatDate = (value) => value ? new Date(value).toLocaleString() : "—";
const parseJson = (value, fallback) => { try { const parsed = JSON.parse(value); return parsed ?? fallback; } catch { return fallback; } };

function shell(page) {
  const route = state.route;
  const nav = ["projects", "image", "chat", "canvas", "assets"].map((key) => `<button data-route="${key}" class="${route === key ? "is-active" : ""}"><span class="hh-icon">${icons[key]}</span>${routeLabels[key]}</button>`).join("");
  return `<aside class="hh-nav"><div class="hh-brand"><img src="/huahai-canvas.png" alt="花海画布"><span>花海画布</span></div><button class="hh-nav__fold" data-action="toggle-other">›&nbsp;&nbsp;其他功能</button><nav>${nav}</nav><div class="hh-nav__other" hidden><button data-route="settings"><span class="hh-icon">⚙</span>性能设置</button></div><div class="hh-nav__space"></div><div class="hh-nav__bottom"><button data-action="announcements"><span class="hh-icon">${icons.announcements}</span>公告</button><button data-route="api"><span class="hh-icon">${icons.api}</span>API 设置</button><button data-route="settings"><span class="hh-icon">${icons.settings}</span>更多设置</button><button data-action="homepage"><span class="hh-icon">${icons.homepage}</span>项目主页</button></div><div class="hh-nav__version">v5.8.0 · 本地数据仅存 F 盘</div></aside><main class="hh-main">${page}</main>`;
}

function projectsPage() {
  const cards = state.projects.length ? state.projects.map((project) => `<article class="hh-card hh-project"><h2>${escapeHtml(project.name)}</h2><p>${project.nodeCount || 0} 个节点 · 更新于 ${escapeHtml(formatDate(project.updatedAt))}</p><div class="hh-project__actions"><button class="hh-button--primary" data-open-project="${project.id}">打开画布</button><button data-rename-project="${project.id}">重命名</button><button class="hh-button--danger" data-delete-project="${project.id}">删除</button></div></article>`).join("") : `<div class="hh-card hh-empty">还没有项目。创建一个项目后即可使用无限画布、生图和素材库。</div>`;
  return `<section class="hh-page"><header class="hh-page__head"><div><h1>项目管理</h1><p>项目、画布和本地聊天记录都保存在 F 盘。</p></div><div class="hh-actions"><button data-action="import-project">导入项目</button><button class="hh-button--primary" data-action="new-project">＋ 新建项目</button></div></header><div class="hh-projects">${cards}</div></section>`;
}

function imagePage() {
  const result = state.generated?.result ? `<div class="hh-result"><img src="${escapeHtml(state.generated.result)}" alt="生成结果"><div class="hh-actions"><button data-action="result-to-asset">加入素材库</button><button class="hh-button--primary" data-action="result-to-canvas">加入当前画布</button></div></div>` : "";
  return `<section class="hh-page"><header class="hh-page__head"><div><h1>在线生图</h1><p>提交前会确认可能产生的服务费用，密钥仅保存在本机 F 盘。</p></div></header><form class="hh-card hh-form" data-form="image"><label class="hh-field">通道 ID<input name="provider" placeholder="例如 my-openai" required></label><div class="hh-form__row"><label class="hh-field">模型<input name="model" placeholder="例如 gpt-image-1" required></label><label class="hh-field">尺寸<select name="size"><option>1024x1024</option><option>1536x1024</option><option>1024x1536</option></select></label></div><label class="hh-field">提示词<textarea name="prompt" required placeholder="描述你想生成的画面…"></textarea></label><label class="hh-field">负面提示词（可选）<input name="negative_prompt" placeholder="不希望出现的元素"></label><button class="hh-button--primary" type="submit">生成图片</button></form>${result}</section>`;
}

function chatPage() {
  const sessionButtons = state.sessions.map((session) => `<button data-session="${session.id}" class="${state.session?.id === session.id ? "is-active" : ""}">${escapeHtml(session.title)}</button>`).join("") || `<p class="hh-empty">尚无会话</p>`;
  const messages = (state.messages || []).map((message) => `<article class="hh-message hh-message--${message.role === "user" ? "user" : "assistant"}">${escapeHtml(message.content)}</article>`).join("") || `<p class="hh-empty">开始一个对话。默认只会发送当前项目摘要和选中节点文本。</p>`;
  return `<section class="hh-page hh-chat"><aside class="hh-card hh-chat__sessions"><button class="hh-button--primary" data-action="new-chat">＋ 新建会话</button>${sessionButtons}</aside><section class="hh-card"><header class="hh-page__head" style="padding:16px 20px;margin:0"><div><h1 style="font-size:21px">GPT 对话</h1><p>${state.currentProject ? `当前项目：${escapeHtml(state.currentProject.name)}` : "通用会话"}</p></div></header><div class="hh-chat__messages">${messages}</div><form class="hh-chat__composer" data-form="chat"><label class="hh-field">通道 ID<input name="provider" placeholder="API 设置中的通道 ID" required></label><label class="hh-field">模型<input name="model" placeholder="模型名称" required></label><label class="hh-field"><textarea name="content" required placeholder="输入创作需求…"></textarea></label><label class="hh-field"><span><input type="checkbox" name="context" checked> 附带当前项目摘要与已选节点文本（不发送原图）</span></label><div class="hh-actions"><button class="hh-button--primary" type="submit">发送</button><button type="button" data-action="cancel-chat">取消等待</button></div></form></section></section>`;
}

function assetsPage() {
  const cards = state.assets.map((asset) => `<article class="hh-card hh-asset">${asset.category === "video" ? `<video src="${escapeHtml(asset.filePath)}" preload="metadata" muted></video>` : `<img src="${escapeHtml(asset.filePath)}" loading="lazy" decoding="async" alt="${escapeHtml(asset.name)}">`}<div class="hh-asset__body"><strong>${escapeHtml(asset.name)}</strong><span>${escapeHtml(asset.category)} · ${escapeHtml(asset.tags || "无标签")}</span><div class="hh-project__actions"><button data-asset-canvas="${asset.id}">加入画布</button><button class="hh-button--danger" data-delete-asset="${asset.id}">移除索引</button></div></div></article>`).join("") || `<div class="hh-card hh-empty">素材库为空。在线生图的结果可一键加入这里。</div>`;
  return `<section class="hh-page"><header class="hh-page__head"><div><h1>素材库</h1><p>删除仅移除素材库索引，不删除用户文件。</p></div><div class="hh-actions"><input data-asset-search placeholder="搜索素材或标签"><button data-action="refresh-assets">刷新</button></div></header><div class="hh-assets">${cards}</div></section>`;
}

function apiPage() { return `<section class="hh-page"><header class="hh-page__head"><div><h1>API 设置</h1><p>API Key 仅写入 F 盘本地设置；不会显示、导出或提交到 Git。</p></div></header><form class="hh-card hh-form" data-form="api"><label class="hh-field">通道 ID<input name="provider" required placeholder="例如 my-openai"></label><label class="hh-field">Base URL<input name="baseUrl" required placeholder="https://example.com/v1"></label><label class="hh-field">API Key<input name="apiKey" type="password" autocomplete="new-password" required placeholder="仅本机保存"></label><button class="hh-button--primary" type="submit">保存本地设置</button></form></section>`; }
function settingsPage() { return `<section class="hh-page"><header class="hh-page__head"><div><h1>更多设置</h1><p>性能保护已开启：懒加载、离屏视频暂停和大画布提示。</p></div></header><div class="hh-card hh-form"><label class="hh-field"><span><input type="checkbox" checked disabled> 图片懒加载与异步解码</span></label><label class="hh-field"><span><input type="checkbox" checked disabled> 离屏视频自动暂停（最多 4 个活动视频）</span></label><button data-action="show-storage">查看 F 盘存储说明</button></div></section>`; }

function canvasPage() {
  if (!state.currentProject) return `<section class="hh-page"><div class="hh-card hh-empty"><h1>尚未打开项目</h1><p>请选择一个项目，或新建项目后再进入无限画布。</p><button class="hh-button--primary" data-route="projects">打开项目管理</button></div></section>`;
  const nodes = parseJson(state.currentProject.nodesJson, []);
  const nodeHtml = nodes.map((node) => { const type = node.type || "text"; const data = node.data || {}; const selected = state.selection.has(node.id) ? "is-selected" : ""; const x = Number(node.position?.x || 0); const y = Number(node.position?.y || 0); const media = type.includes("video") ? `<video src="${escapeHtml(data.url || data.videoUrl || "")}" preload="metadata" muted></video>` : type.includes("image") ? `<img src="${escapeHtml(data.url || data.imageUrl || "")}" loading="lazy" decoding="async" alt="">` : ""; return `<article class="hh-node ${selected}" data-node="${node.id}" style="transform:translate(${x}px,${y}px)"><div class="hh-node__head">${escapeHtml(data.label || type)}</div>${media}<div class="hh-node__text">${escapeHtml(data.prompt || data.text || data.label || "")}</div></article>`; }).join("");
  const multiple = state.selection.size >= 2;
  return `<section class="hh-canvas-page"><div class="hh-canvas-toolbar"><strong>${escapeHtml(state.currentProject.name)}</strong><button data-action="add-text">＋ 文字</button><button data-action="add-image">＋ 图片</button><button data-action="add-video">＋ 生视频</button>${multiple ? `<button data-action="connect-video">连接到生视频</button><button data-action="arrange-horizontal">横向排列</button><button data-action="arrange-vertical">纵向排列</button><button data-action="clear-selection">取消选择</button><button data-action="undo-batch">撤销</button><button data-action="redo-batch">重做</button>` : ""}<button data-action="save-canvas">保存</button><button data-action="export-project">导出</button><span>缩放 ${Math.round(state.view.scale * 100)}%</span></div><div class="hh-canvas" data-canvas><div class="hh-canvas__world" style="transform:translate(${state.view.x}px,${state.view.y}px) scale(${state.view.scale})">${nodeHtml}</div><span class="hh-canvas__hint">滚轮缩放 · 拖动空白处平移 · Shift/ Ctrl 多选</span></div></section>`;
}

function render(root) { const pages = { projects: projectsPage, image: imagePage, chat: chatPage, canvas: canvasPage, assets: assetsPage, api: apiPage, settings: settingsPage }; root.innerHTML = shell((pages[state.route] || projectsPage)()); bind(root); }

async function loadProjects() { state.projects = await invoke("list_project_summaries"); }
async function saveProject(project) { const record = await invoke("upsert_project_record", { id: project.id, name: project.name, nodesJson: project.nodesJson, edgesJson: project.edgesJson, viewportJson: project.viewportJson, historyJson: project.historyJson, imagePoolJson: project.imagePoolJson, nodeCount: project.nodeCount }); state.currentProject = record; await loadProjects(); }
function selectedContext() { const nodes = parseJson(state.currentProject?.nodesJson, []); return { project: state.currentProject ? { id: state.currentProject.id, name: state.currentProject.name, nodeCount: nodes.length } : null, selectedNodes: nodes.filter((node) => state.selection.has(node.id)).slice(0, 8).map((node) => ({ id: node.id, type: node.type, text: String(node.data?.prompt || node.data?.text || node.data?.label || "").slice(0, 300) })) }; }
function addCanvasNode(type, data) { const nodes = parseJson(state.currentProject.nodesJson, []); const offset = nodes.length * 28; nodes.push({ id: `${type}-${crypto.randomUUID()}`, type, position: { x: 90 + offset, y: 90 + offset }, data }); state.currentProject.nodesJson = JSON.stringify(nodes); state.currentProject.nodeCount = nodes.length; return saveProject(state.currentProject); }

function bind(root) {
  root.querySelectorAll("[data-route]").forEach((button) => button.addEventListener("click", async () => { state.route = button.dataset.route; if (state.route === "projects") await loadProjects(); if (state.route === "assets") state.assets = await invoke("list_assets", { categoryFilter: "", search: "" }); if (state.route === "chat") await loadChat(); render(root); }));
  root.querySelector("[data-action=toggle-other]")?.addEventListener("click", (event) => { const other = root.querySelector(".hh-nav__other"); other.hidden = !other.hidden; event.currentTarget.setAttribute("aria-expanded", String(!other.hidden)); });
  root.querySelector("[data-action=announcements]")?.addEventListener("click", () => window.dispatchEvent(new CustomEvent("huahai:open-announcements")));
  root.querySelector("[data-action=homepage]")?.addEventListener("click", () => window.open(projectHomepage, "_blank", "noopener,noreferrer"));
  root.querySelector("[data-action=new-project]")?.addEventListener("click", async () => { const name = window.prompt("项目名称", "未命名项目"); if (!name?.trim()) return; await saveProject({ id: crypto.randomUUID(), name: name.trim(), nodesJson: "[]", edgesJson: "[]", viewportJson: "{}", historyJson: "[]", imagePoolJson: "[]", nodeCount: 0 }); state.route = "canvas"; render(root); });
  root.querySelectorAll("[data-open-project]").forEach((button) => button.addEventListener("click", async () => { state.currentProject = await invoke("get_project_record", { id: button.dataset.openProject }); state.route = "canvas"; state.selection.clear(); render(root); }));
  root.querySelectorAll("[data-rename-project]").forEach((button) => button.addEventListener("click", async () => { const project = state.projects.find((item) => item.id === button.dataset.renameProject); const name = window.prompt("新的项目名称", project?.name || ""); if (name?.trim()) { await invoke("rename_project_record", { id: button.dataset.renameProject, name: name.trim() }); await loadProjects(); render(root); } }));
  root.querySelectorAll("[data-delete-project]").forEach((button) => button.addEventListener("click", async () => { if (!window.confirm("删除项目记录？此操作不会删除已导出的文件。")) return; await invoke("delete_project_record", { id: button.dataset.deleteProject }); if (state.currentProject?.id === button.dataset.deleteProject) state.currentProject = null; await loadProjects(); render(root); }));
  root.querySelector("[data-form=image]")?.addEventListener("submit", async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (!window.confirm("本次生成可能会产生服务费用。确认继续吗？")) return; try { const jobId = await invoke("submit_generate_image_job", { payload: JSON.stringify({ provider_id: data.provider, model: data.model, prompt: data.prompt, negative_prompt: data.negative_prompt || undefined, size: data.size, n: 1 }) }); state.generated = { jobId }; await pollImageJob(root, jobId); } catch (error) { toast(`生成失败：${String(error)}`, "error"); } });
  root.querySelector("[data-form=api]")?.addEventListener("submit", async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await invoke("set_base_url", { provider: data.provider, url: data.baseUrl }); await invoke("set_api_key", { provider: data.provider, key: data.apiKey }); event.currentTarget.reset(); toast("API 设置已保存在本机 F 盘。", "success"); } catch (error) { toast(`保存失败：${String(error)}`, "error"); } });
  root.querySelector("[data-action=result-to-asset]")?.addEventListener("click", async () => { if (!state.generated?.result) return; await invoke("add_asset", { name: `生成图片 ${new Date().toLocaleString()}`, category: "image", tags: "生成", filePath: state.generated.result, sourceType: "online-image", sourceNodeId: null }); toast("已加入素材库。", "success"); });
  root.querySelector("[data-action=result-to-canvas]")?.addEventListener("click", async () => { if (!state.currentProject) { toast("请先打开一个项目。", "info"); return; } await addCanvasNode("image", { label: "在线生成图片", imageUrl: state.generated.result, url: state.generated.result, prompt: "在线生成" }); state.route = "canvas"; render(root); });
  root.querySelector("[data-action=refresh-assets]")?.addEventListener("click", async () => { state.assets = await invoke("list_assets", { categoryFilter: "", search: root.querySelector("[data-asset-search]")?.value || "" }); render(root); });
  root.querySelectorAll("[data-delete-asset]").forEach((button) => button.addEventListener("click", async () => { if (window.confirm("仅移除素材库索引，不删除文件。继续吗？")) { await invoke("delete_asset", { id: button.dataset.deleteAsset }); state.assets = await invoke("list_assets", { categoryFilter: "", search: "" }); render(root); } }));
  root.querySelectorAll("[data-asset-canvas]").forEach((button) => button.addEventListener("click", async () => { const asset = state.assets.find((item) => item.id === button.dataset.assetCanvas); if (!state.currentProject) { toast("请先打开一个项目。", "info"); return; } await addCanvasNode(asset.category === "video" ? "video" : "image", { label: asset.name, url: asset.filePath, imageUrl: asset.filePath, videoUrl: asset.filePath }); state.route = "canvas"; render(root); }));
  bindCanvas(root);
  root.querySelector("[data-action=new-chat]")?.addEventListener("click", async () => { state.session = await invoke("create_chat_session", { projectId: state.currentProject?.id || null, title: "新对话", model: "" }); await loadChat(); render(root); });
  root.querySelectorAll("[data-session]").forEach((button) => button.addEventListener("click", async () => { state.session = state.sessions.find((item) => item.id === button.dataset.session); state.messages = await invoke("list_chat_messages", { sessionId: state.session.id }); render(root); }));
  root.querySelector("[data-form=chat]")?.addEventListener("submit", async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (!state.session) state.session = await invoke("create_chat_session", { projectId: state.currentProject?.id || null, title: String(data.content).slice(0, 32), model: data.model }); const context = data.context ? selectedContext() : {}; try { const reply = await invoke("send_chat_message", { sessionId: state.session.id, providerId: data.provider, model: data.model, content: data.content, contextJson: JSON.stringify(context) }); state.messages = [...(state.messages || []), { role: "user", content: data.content }, reply]; event.currentTarget.reset(); render(root); } catch (error) { toast(`对话失败：${String(error)}`, "error"); } });
}

async function pollImageJob(root, jobId) { for (let attempt = 0; attempt < 120; attempt += 1) { const job = await invoke("get_generate_image_job", { jobId }); state.generated = job; render(root); if (job.status === "succeeded" || job.status === "failed") { if (job.status === "failed") toast(job.error || "图片生成失败", "error"); return; } await new Promise((resolve) => setTimeout(resolve, 2000)); } toast("生成任务超时，请稍后在服务端查看。", "error"); }
async function loadChat() { state.sessions = await invoke("list_chat_sessions", { projectId: state.currentProject?.id || null }); if (!state.session && state.sessions.length) state.session = state.sessions[0]; state.messages = state.session ? await invoke("list_chat_messages", { sessionId: state.session.id }) : []; }

function bindCanvas(root) {
  const canvas = root.querySelector("[data-canvas]"); if (!canvas) return;
  let panning = null; let dragging = null;
  canvas.addEventListener("wheel", (event) => { event.preventDefault(); const next = Math.min(2.2, Math.max(.35, state.view.scale * (event.deltaY > 0 ? .9 : 1.1))); state.view.scale = next; render(root); }, { passive: false });
  canvas.addEventListener("pointerdown", (event) => { const node = event.target.closest("[data-node]"); if (node) { const id = node.dataset.node; if (!event.ctrlKey && !event.shiftKey) state.selection = new Set([id]); else state.selection.has(id) ? state.selection.delete(id) : state.selection.add(id); dragging = { id, x: event.clientX, y: event.clientY }; } else panning = { x: event.clientX, y: event.clientY, originX: state.view.x, originY: state.view.y }; canvas.setPointerCapture(event.pointerId); render(root); });
  canvas.addEventListener("pointermove", (event) => { if (panning) { state.view.x = panning.originX + event.clientX - panning.x; state.view.y = panning.originY + event.clientY - panning.y; root.querySelector(".hh-canvas__world").style.transform = `translate(${state.view.x}px,${state.view.y}px) scale(${state.view.scale})`; } if (dragging) { const nodes = parseJson(state.currentProject.nodesJson, []); const node = nodes.find((item) => item.id === dragging.id); if (node) { node.position = node.position || {}; node.position.x = Number(node.position.x || 0) + (event.clientX - dragging.x) / state.view.scale; node.position.y = Number(node.position.y || 0) + (event.clientY - dragging.y) / state.view.scale; dragging.x = event.clientX; dragging.y = event.clientY; state.currentProject.nodesJson = JSON.stringify(nodes); const element = root.querySelector(`[data-node="${dragging.id}"]`); element.style.transform = `translate(${node.position.x}px,${node.position.y}px)`; } } });
  canvas.addEventListener("pointerup", async () => { if (dragging) await saveProject(state.currentProject); panning = null; dragging = null; });
  root.querySelector("[data-action=add-text]")?.addEventListener("click", async () => { const text = window.prompt("文字内容", "新的创作说明"); if (text) { await addCanvasNode("text", { label: "文字", text }); render(root); } });
  root.querySelector("[data-action=add-image]")?.addEventListener("click", async () => { const url = window.prompt("图片 URL 或 F 盘图片路径"); if (url) { await addCanvasNode("image", { label: "图片", imageUrl: url, url }); render(root); } });
  root.querySelector("[data-action=add-video]")?.addEventListener("click", async () => { await addCanvasNode("video", { label: "生视频", videoMode: "image2video" }); render(root); });
  root.querySelector("[data-action=clear-selection]")?.addEventListener("click", () => { state.selection.clear(); render(root); });
  root.querySelector("[data-action=save-canvas]")?.addEventListener("click", async () => { await saveProject(state.currentProject); toast("画布已保存。", "success"); });
  root.querySelector("[data-action=connect-video]")?.addEventListener("click", () => batchAction(root, "connect-video"));
  root.querySelector("[data-action=arrange-horizontal]")?.addEventListener("click", () => batchAction(root, "arrange-horizontal"));
  root.querySelector("[data-action=arrange-vertical]")?.addEventListener("click", () => batchAction(root, "arrange-vertical"));
  root.querySelector("[data-action=undo-batch]")?.addEventListener("click", () => historyAction(root, "undo_last_canvas_batch_action"));
  root.querySelector("[data-action=redo-batch]")?.addEventListener("click", () => historyAction(root, "redo_last_canvas_batch_action"));
}
async function batchAction(root, action) { try { const ids = [...state.selection]; const result = await invoke("apply_canvas_batch_action", { projectId: state.currentProject.id, selectedNodeIds: ids, action, targetVideoNodeId: null }); state.currentProject = result; await loadProjects(); render(root); toast("批量操作已保存，可撤销。", "success"); } catch (error) { toast(`批量操作未执行：${String(error)}`, "error"); } }
async function historyAction(root, command) { try { state.currentProject = await invoke(command, { projectId: state.currentProject.id }); render(root); } catch (error) { toast(String(error), "info"); } }

export function installWorkspace({ openAnnouncements }) {
  const legacyRoot = document.getElementById("root");
  const root = document.createElement("div"); root.id = "huahai-workspace"; document.body.append(root);
  window.addEventListener("huahai:open-announcements", openAnnouncements);
  loadProjects().then(() => { if (legacyRoot) legacyRoot.hidden = true; render(root); }).catch((error) => { root.remove(); toast(`花海工作区启动失败，已保留旧界面：${String(error)}`, "error"); });
}
